[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[programs.localnet]
oracles = "4fku27SVF5v7ee7qKGzA8nteFqFmow9HNw44JaV8NCaW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/dc/.config/solana/new_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"