[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
flexxcash_oracle = "4fku27SVF5v7ee7qKGzA8nteFqFmow9HNw44JaV8NCaW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
